---
storage:
  driver:
    record:
      key:
        enabled: boolean
      headers: map
      timeoutMillis: long
    request:
      size: int
    buffer:
      memory: long
    compression:
      type: string
  net:
    sndBuf: int
    rcvBuf: int
    linger: int
    node:
      addrs: list
      port: int
